#ifndef INTTYPES_H
#define INTTYPES_H

#include <stdint.h>

#define PRId16 "d"
#define PRId32 "d"
#define PRId64 "l" "d"
#define PRId8 "d"
#define PRIdFAST16 "l" "d"
#define PRIdFAST32 "l" "d"
#define PRIdFAST64 "l" "d"
#define PRIdFAST8 "d"
#define PRIdLEAST16 "d"
#define PRIdLEAST32 "d"
#define PRIdLEAST64 "l" "d"
#define PRIdLEAST8 "d"
#define PRIi16 "i"
#define PRIi32 "i"
#define PRIi64 "l" "i"
#define PRIi8 "i"
#define PRIiFAST16 "l" "i"
#define PRIiFAST32 "l" "i"
#define PRIiFAST64 "l" "i"
#define PRIiFAST8 "i"
#define PRIiLEAST16 "i"
#define PRIiLEAST32 "i"
#define PRIiLEAST64 "l" "i"
#define PRIiLEAST8 "i"
#define PRIo16 "o"
#define PRIo32 "o"
#define PRIo64 "l" "o"
#define PRIo8 "o"
#define PRIoFAST16 "l" "o"
#define PRIoFAST32 "l" "o"
#define PRIoFAST64 "l" "o"
#define PRIoFAST8 "o"
#define PRIoLEAST16 "o"
#define PRIoLEAST32 "o"
#define PRIoLEAST64 "l" "o"
#define PRIoLEAST8 "o"
#define PRIu16 "u"
#define PRIu32 "u"
#define PRIu64 "l" "u"
#define PRIu8 "u"
#define PRIuFAST16 "l" "u"
#define PRIuFAST32 "l" "u"
#define PRIuFAST64 "l" "u"
#define PRIuFAST8 "u"
#define PRIuLEAST16 "u"
#define PRIuLEAST32 "u"
#define PRIuLEAST64 "l" "u"
#define PRIuLEAST8 "u"
#define PRIx16 "x"
#define PRIX16 "X"
#define PRIx32 "x"
#define PRIX32 "X"
#define PRIx64 "l" "x"
#define PRIX64 "l" "X"
#define PRIx8 "x"
#define PRIX8 "X"
#define PRIxFAST16 "l" "x"
#define PRIXFAST16 "l" "X"
#define PRIxFAST32 "l" "x"
#define PRIXFAST32 "l" "X"
#define PRIxFAST64 "l" "x"
#define PRIXFAST64 "l" "X"
#define PRIxFAST8 "x"
#define PRIXFAST8 "X"
#define PRIxLEAST16 "x"
#define PRIXLEAST16 "X"
#define PRIxLEAST32 "x"
#define PRIXLEAST32 "X"
#define PRIxLEAST64 "l" "x"
#define PRIXLEAST64 "l" "X"
#define PRIxLEAST8 "x"
#define PRIXLEAST8 "X"
#define SCNd16 "hd"
#define SCNd32 "d"
#define SCNd64 "l" "d"
#define SCNd8 "hhd"
#define SCNdFAST16 "l" "d"
#define SCNdFAST32 "l" "d"
#define SCNdFAST64 "l" "d"
#define SCNdFAST8 "hhd"
#define SCNdLEAST16 "hd"
#define SCNdLEAST32 "d"
#define SCNdLEAST64 "l" "d"
#define SCNdLEAST8 "hhd"
#define SCNi16 "hi"
#define SCNi32 "i"
#define SCNi64 "l" "i"
#define SCNi8 "hhi"
#define SCNiFAST16 "l" "i"
#define SCNiFAST32 "l" "i"
#define SCNiFAST64 "l" "i"
#define SCNiFAST8 "hhi"
#define SCNiLEAST16 "hi"
#define SCNiLEAST32 "i"
#define SCNiLEAST64 "l" "i"
#define SCNiLEAST8 "hhi"
#define SCNo16 "ho"
#define SCNo32 "o"
#define SCNo64 "l" "o"
#define SCNo8 "hho"
#define SCNoFAST16 "l" "o"
#define SCNoFAST32 "l" "o"
#define SCNoFAST64 "l" "o"
#define SCNoFAST8 "hho"
#define SCNoLEAST16 "ho"
#define SCNoLEAST32 "o"
#define SCNoLEAST64 "l" "o"
#define SCNoLEAST8 "hho"
#define SCNu16 "hu"
#define SCNu32 "u"
#define SCNu64 "l" "u"
#define SCNu8 "hhu"
#define SCNuFAST16 "l" "u"
#define SCNuFAST32 "l" "u"
#define SCNuFAST64 "l" "u"
#define SCNuFAST8 "hhu"
#define SCNuLEAST16 "hu"
#define SCNuLEAST32 "u"
#define SCNuLEAST64 "l" "u"
#define SCNuLEAST8 "hhu"
#define SCNx16 "hx"
#define SCNx32 "x"
#define SCNx64 "l" "x"
#define SCNx8 "hhx"
#define SCNxFAST16 "l" "x"
#define SCNxFAST32 "l" "x"
#define SCNxFAST64 "l" "x"
#define SCNxFAST8 "hhx"
#define SCNxLEAST16 "hx"
#define SCNxLEAST32 "x"
#define SCNxLEAST64 "l" "x"
#define SCNxLEAST8 "hhx"
 #define PRIdMAX "l" "d"
#define PRIiMAX "l" "i"
#define PRIoMAX "l" "o"
#define PRIuMAX "l" "u"
#define PRIxMAX "l" "x"
#define PRIXMAX "l" "X"
#define SCNdMAX "l" "d"
#define SCNiMAX "l" "i"
#define SCNoMAX "l" "o"
#define SCNuMAX "l" "u"
#define SCNxMAX "l" "x"

#define stroimax(a, b, c) (intmax_t)stroll(a, b, c)
#define stroumax(a, b, c) (uintmax_t)stroull(a, b, c)

#endif